import "./globals.css";
import Footer from "@/components/footer/Footer";
import { Container } from "@mui/material";
import ThemeComponent from "@/components/layout/themeComponent";
import Navbar from "@/components/navbar/Navbar";

export const metadata = {
  title: "Siber Yavuzlar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeComponent>
          <Navbar />
          <Container maxWidth="xl">{children}</Container>
          <Footer />
        </ThemeComponent>
      </body>
    </html>
  );
}
