import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { Container } from "@mui/material";

// const theme = createTheme({
//   palette: {
//     primary: {
//       main: colors.orange[500],
//     },
//     secondary: {
//       main: "#73CD07",
//     },
//   },
// });

export const metadata = {
  title: "Siber Yavuzlar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <ThemeProvider theme={theme}> */}
        <Navbar />
        <Container maxWidth="xl">{children}</Container>
        <Footer />
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
